services:
  vllm:
    build: .
    image: docker.internal.phis.nl/qwen3_6_35b_a3b_nvfp4_vllm:0.19.1
    platform: linux/arm64
    network_mode: host
    ipc: host
    environment:
      HF_HOME: /models
      HF_HUB_CACHE: /models
    volumes:
      - ${HOME}/models:/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
