services:
  vllm:
    build: .
    image: docker.internal.phis.nl/gemma4_26b_a4b_nvfp4_vllm:0.19.0
    network_mode: host
    ipc: host
    environment:
      VLLM_NVFP4_GEMM_BACKEND: marlin
      HF_HOME: /models
      HF_HUB_CACHE: /models
    volumes:
      - ${HOME}/models:/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
